#!/usr/bin/env bash
# docker run --rm --gpus all --net=host --ipc=host -ti nemo:latest bash
docker run --rm -v /data:/data --net=host --ipc=host --gpus=all -w /data -ti nemo:latest jupyter lab  --ip=0.0.0.0 --allow-root
